# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Muhammad Habibullah Galih Tri Aji
email: your_email@example.com
description: PhD Researcher in Marine Geochemistry, Marine Geology and Paleoceanography
baseurl: ""
url: "https://mhgta10.github.io"

image: /assets/img/avatar/profile.jpg
image_alt: Muhammad Habibullah Galih Tri Aji

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#

author: Muhammad Habibullah Galih Tri Aji

profile_image: /assets/img/avatar/profile.jpg

occupation: PhD Researcher

snippet: >
  Research interests include marine geochemistry,
  chemical weathering, carbon cycle dynamics,
  paleoceanography, and Earth system evolution.

twitter:
github: mhgta10
linkedin:
stackoverflow:
website: "https://mhgta10.github.io"
codepen:
medium:
email: your_email@example.com
keybase:
pgp:
ctftime:
phonenumber:

# =======================================#
# --------- UI THEMES -------------------#
#========================================#

ui_theme: abyss

# =======================================#
# -----------HOME PAGE SETTINGS----------#
#========================================#

home_option: education

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#00334e"
footer-color: "#00334e"
color-scheme: "#00334e"
card-color: "#00334e"
animate: true
